export default {
  "index": "Overview",
  "admin-docs-governance": "Admin Docs Governance",
  "agents": "Agents",
  "api": "Api",
  "app-feel-checklist": "App Feel Checklist",
  "app-feel-components": "App Feel Components",
  "app-feel-guide": "App Feel Guide",
  "auth": "Auth",
  "business": "Business",
  "database": "Database",
  "design": "Design",
  "dev-department": "Dev Department",
  "docs-index": "Docs Index",
  "docs-plan": "Docs Plan",
  "engineering": "Engineering",
  "features": "Features",
  "guides": "Guides",
  "help": "Help",
  "i18n": "I18n",
  "launch-status": "Launch Status",
  "launch": "Launch",
  "payments": "Payments",
  "payments-overview": "Payments Overview",
  "platform": "Platform",
  "policies": "Policies",
  "production": "Production",
  "prompt-guide": "Prompt Guide",
  "public-docs": "Public Docs",
  "refactor": "Refactor",
  "routes": "Routes",
  "ui-ux-plan": "Ui Ux Plan",
  "workflow": "Workflow",
}
