export default {
  "index": "Overview",
  "api": "Api",
  "auth": "Auth",
  "database": "Database",
  "design": "Design",
  "engineering": "Engineering",
  "frontend": "Frontend",
  "help": "Help",
  "i18n": "I18n",
  "payments": "Payments",
  "policies": "Policies",
  "project": "Project",
  "public-docs": "Public Docs",
  "qa": "Qa",
  "reference": "Reference",
  "risk": "Risk",
  "routes": "Routes",
  "workflow": "Workflow",
}
