export default {
  "index": "Overview",
  "api": "Api",
  "auth": "Auth",
  "business": "Business",
  "database": "Database",
  "engineering": "Engineering",
  "features": "Features",
  "guides": "Guides",
  "help": "Help",
  "i18n": "I18n",
  "payments": "Payments",
  "platform": "Platform",
  "policies": "Policies",
  "production": "Production",
  "prompts": "Prompts",
  "public-docs": "Public Docs",
  "routes": "Routes",
  "runbooks": "Runbooks",
  "testing": "Testing",
  "workflow": "Workflow",
}
