import { Accessibility, AlignLeft, Archive, ArrowLeft, ArrowRight, ArrowUpDown, ArrowUpRight, AtSign, Baby, BadgeCheck, Ban, Bell, BellRing, Bird, Bold, BookOpen, Bot, Briefcase, Brush, Bug, Building2, Calendar, Camera, Car, ChartColumn, ChartLine, Check, CheckCheck, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Circle, CircleAlert, CircleCheck, CircleDollarSign, CircleHelp, CircleUser, CircleUserRound, CircleX, Clock, CloudCheck, CloudUpload, Code, Computer, Cookie, Copy, CreditCard, Crosshair, Crown, Database, Diamond, Dog, DollarSign, Download, Dribbble, Dumbbell, Ellipsis, Eye, EyeOff, Facebook, FileText, Film, Fingerprint, Flag, Flame, FlaskConical, Flower, Folder, FolderOpen, Footprints, Funnel, Gamepad2, Gavel, Gift, Globe, GraduationCap, Guitar, Hammer, Handbag, Handshake, Headphones, Headset, Heart, HeartCrack, House, IdCard, Image, Inbox, Info, Instagram, Italic, Key, KeyRound, Laptop, LayoutGrid, Leaf, LifeBuoy, Lightbulb, Link, List, Loader, LoaderCircle, Lock, LogIn, LogOut, Mail, MapPin, Mars, Medal, Megaphone, Menu, MessageCircle, MessageCircleMore, Minus, Monitor, Music, Music2, Package, Palette, PartyPopper, Pause, PawPrint, Pencil, PencilLine, Percent, Phone, Pill, Plane, Play, Plus, Printer, Receipt, RefreshCcw, RefreshCw, Rocket, Rows3, Save, Scale, Search, Send, Settings, Settings2, Share, Share2, Shield, ShieldCheck, Shirt, ShoppingBag, ShoppingCart, SlidersHorizontal, Smartphone, Sparkles, SquareArrowOutUpRight, Star, Store, Tablet, Tag, Target, Ticket, Trash, TrendingDown, TrendingUp, TriangleAlert, Trophy, Truck, Tv, Type, User, UserCheck, UserPlus, Users, Utensils, Venus, Video, Watch, Wrench, X, Youtube, Zap } from "lucide-react";
import type { LucideIcon } from "lucide-react";
import { createLegacyIconPicker } from "@/lib/icons/compat";

const ICONS = {
  Airplane: Plane,
  AlignLeft,
  Archive,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  ArrowUpRight,
  AtSign,
  Baby,
  BadgeCheck,
  Ban,
  Barbell: Dumbbell,
  Basketball: Dribbble,
  Bell,
  BellRing,
  Bold,
  BookOpen,
  Boot: Footprints,
  Briefcase,
  Bug,
  Buildings: Building2,
  Calendar,
  CalendarBlank: Calendar,
  Camera,
  Car,
  ChartColumn,
  ChartLine,
  Check,
  Checks: CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleUser,
  CircleX,
  Clock,
  CloudCheck,
  CloudUpload,
  CoatHanger: Shirt,
  Code,
  Computer,
  Cookie,
  Copy,
  CreditCard,
  Crosshair,
  Crown,
  Database,
  DeviceTablet: Tablet,
  Diamond,
  Dog,
  DollarSign,
  Download,
  Dress: Shirt,
  Ellipsis,
  Eye,
  EyeOff,
  Facebook,
  FileText,
  FilmStrip: Film,
  Fingerprint,
  Fire: Flame,
  Flag,
  Flask: FlaskConical,
  FloppyDisk: Save,
  Flower,
  Folder,
  FolderOpen,
  Funnel,
  Gamepad2,
  Gavel,
  GenderFemale: Venus,
  GenderMale: Mars,
  Gift,
  Globe,
  GraduationCap,
  Guitar,
  Hammer,
  Handbag,
  Handshake,
  Headphones,
  Headset,
  Heart,
  HeartCrack,
  Hoodie: Shirt,
  House,
  IdCard,
  Image,
  Info,
  Instagram,
  Italic,
  Key,
  Laptop,
  LayoutGrid,
  Leaf,
  LifeBuoy,
  Lightbulb,
  Link,
  List,
  Loader,
  LoaderCircle,
  Lock,
  LockKey: KeyRound,
  LogIn,
  LogOut,
  MagnifyingGlassPlus: Search,
  Mail,
  MapPin,
  Medal,
  Megaphone,
  Menu,
  MessageCircle,
  MessageCircleMore,
  Minus,
  Monitor,
  Music,
  Package,
  PaintBrush: Brush,
  Palette,
  Pants: Shirt,
  PartyPopper,
  Pause,
  PawPrint,
  Pencil,
  PencilLine,
  Percent,
  Phone,
  Pill,
  Play,
  Plus,
  Printer,
  Prohibit: Ban,
  Question: CircleHelp,
  Receipt,
  RefreshCcw,
  RefreshCw,
  Robot: Bot,
  Rocket,
  Rows3,
  Scales: Scale,
  Search,
  SearchPlus: Search,
  Send,
  Settings,
  Settings2,
  Share,
  Share2,
  Shield,
  ShieldCheck,
  ShieldStar: Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  SlidersHorizontal,
  Smartphone,
  Sneaker: Shirt,
  Sparkles,
  SquareArrowOutUpRight,
  Star,
  Store,
  Tag,
  Target,
  Television: Tv,
  Ticket,
  TiktokLogo: Music2,
  Trash,
  Tray: Inbox,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Trophy,
  Truck,
  TwitterLogo: Bird,
  Type,
  User,
  UserCheck,
  UserCircleCheck: CircleUserRound,
  UserPlus,
  Users,
  Utensils,
  Video,
  Watch,
  Wheelchair: Accessibility,
  Wrench,
  X,
  Youtube,
  Zap,
} satisfies Record<string, LucideIcon>;

const FALLBACK_ICON: LucideIcon = Circle;

export function createLucideLegacyPicker() {
  return createLegacyIconPicker(ICONS, FALLBACK_ICON);
}
