export default {
  "index": "Overview",
  "00-INDEX": "00 INDEX",
  "boosts": "Boosts",
  "competitors": "Competitors",
  "decisions": "Decisions",
  "guardrails": "Guardrails",
  "investors": "Investors",
  "monetization": "Monetization",
  "ops": "Ops",
  "pricing": "Pricing",
  "product": "Product",
  "roadmap": "Roadmap",
  "specs": "Specs",
}
