import { ReactNode } from "react"
import {
  Monitor,
  Laptop,
  Lightbulb,
  GameController,
  TShirt,
  House,
  ForkKnife,
  Barbell,
  PaintBrush,
  Gift,
  BookOpen,
  Car,
  Heart,
  Baby,
  Dog,
  DeviceMobile,
  Watch,
  Headphones,
  Camera,
  Television,
  MusicNotes,
  Briefcase,
  ShoppingCart,
  Diamond,
  Palette,
  Pill,
  GraduationCap,
  Guitar,
  FilmStrip,
  Flask,
  Trophy,
  Hammer,
  Flower,
  ShoppingBag,
  Code,
  Leaf,
  Tag,
} from "@phosphor-icons/react"

// Centralized icon mapping for L0/L1 categories used by mega menu and subheader.
// Keep UI renderers free of bulky data objects.
export const categoryIconMap: Record<string, ReactNode> = {
  electronics: <Monitor size={20} weight="regular" className="mega-menu-icon" />,
  computers: <Laptop size={20} weight="regular" className="mega-menu-icon" />,
  "smart-home": <Lightbulb size={20} weight="regular" className="mega-menu-icon" />,
  gaming: <GameController size={20} weight="regular" className="mega-menu-icon" />,
  fashion: <TShirt size={20} weight="regular" className="mega-menu-icon" />,
  home: <House size={20} weight="regular" className="mega-menu-icon" />,
  "home-kitchen": <ForkKnife size={20} weight="regular" className="mega-menu-icon" />,
  sports: <Barbell size={20} weight="regular" className="mega-menu-icon" />,
  "sports-outdoors": <Barbell size={20} weight="regular" className="mega-menu-icon" />,
  beauty: <PaintBrush size={20} weight="regular" className="mega-menu-icon" />,
  toys: <Gift size={20} weight="regular" className="mega-menu-icon" />,
  books: <BookOpen size={20} weight="regular" className="mega-menu-icon" />,
  automotive: <Car size={20} weight="regular" className="mega-menu-icon" />,
  health: <Heart size={20} weight="regular" className="mega-menu-icon" />,
  baby: <Baby size={20} weight="regular" className="mega-menu-icon" />,
  pets: <Dog size={20} weight="regular" className="mega-menu-icon" />,
  "pet-supplies": <Dog size={20} weight="regular" className="mega-menu-icon" />,
  tools: <Hammer size={20} weight="regular" className="mega-menu-icon" />,
  lighting: <Lightbulb size={20} weight="regular" className="mega-menu-icon" />,
  phones: <DeviceMobile size={20} weight="regular" className="mega-menu-icon" />,
  watches: <Watch size={20} weight="regular" className="mega-menu-icon" />,
  audio: <Headphones size={20} weight="regular" className="mega-menu-icon" />,
  cameras: <Camera size={20} weight="regular" className="mega-menu-icon" />,
  tv: <Television size={20} weight="regular" className="mega-menu-icon" />,
  music: <MusicNotes size={20} weight="regular" className="mega-menu-icon" />,
  office: <Briefcase size={20} weight="regular" className="mega-menu-icon" />,
  garden: <Flower size={20} weight="regular" className="mega-menu-icon" />,
  "garden-outdoor": <Flower size={20} weight="regular" className="mega-menu-icon" />,
  "software-services": <Code size={20} weight="regular" className="mega-menu-icon" />,
  grocery: <ShoppingCart size={20} weight="regular" className="mega-menu-icon" />,
  "jewelry-watches": <Diamond size={20} weight="regular" className="mega-menu-icon" />,
  handmade: <Palette size={20} weight="regular" className="mega-menu-icon" />,
  "health-wellness": <Pill size={20} weight="regular" className="mega-menu-icon" />,
  "cbd-wellness": <Leaf size={20} weight="regular" className="mega-menu-icon" />,
  "office-school": <GraduationCap size={20} weight="regular" className="mega-menu-icon" />,
  "musical-instruments": <Guitar size={20} weight="regular" className="mega-menu-icon" />,
  "movies-music": <FilmStrip size={20} weight="regular" className="mega-menu-icon" />,
  "industrial-scientific": <Flask size={20} weight="regular" className="mega-menu-icon" />,
  collectibles: <Trophy size={20} weight="regular" className="mega-menu-icon" />,
  "baby-kids": <Baby size={20} weight="regular" className="mega-menu-icon" />,
  "tools-home": <Hammer size={20} weight="regular" className="mega-menu-icon" />,
  "e-mobility": <Leaf size={20} weight="regular" className="mega-menu-icon" />,
  services: <Briefcase size={20} weight="regular" className="mega-menu-icon" />,
  "bulgarian-traditional": <ForkKnife size={20} weight="regular" className="mega-menu-icon" />,
  wholesale: <ShoppingBag size={20} weight="regular" className="mega-menu-icon" />,
  software: <Code size={20} weight="regular" className="mega-menu-icon" />,
  "real-estate": <House size={20} weight="regular" className="mega-menu-icon" />,
  hobbies: <Guitar size={20} weight="regular" className="mega-menu-icon" />,
  deals: <Tag size={20} weight="regular" className="mega-menu-icon" />,
}

export function getCategoryIcon(
  slug: string,
  fallback: ReactNode = <ShoppingBag size={20} weight="regular" className="mega-menu-icon" />
) {
  return categoryIconMap[slug] || fallback
}
