
-- MASSIVE L3 RESTORATION - PETS, KIDS, AUTOMOTIVE
-- Dogs L3
INSERT INTO categories (id, name, slug, parent_id, icon, display_order) VALUES
(gen_random_uuid(), 'Dog Food', 'dog-food', (SELECT id FROM categories WHERE slug = 'dogs'), '🦴', 1),
(gen_random_uuid(), 'Dog Treats', 'dog-treats', (SELECT id FROM categories WHERE slug = 'dogs'), '🦴', 2),
(gen_random_uuid(), 'Dog Toys', 'dog-toys', (SELECT id FROM categories WHERE slug = 'dogs'), '🎾', 3),
(gen_random_uuid(), 'Dog Beds & Furniture', 'dog-beds', (SELECT id FROM categories WHERE slug = 'dogs'), '🛏️', 4),
(gen_random_uuid(), 'Dog Collars & Leashes', 'dog-collars', (SELECT id FROM categories WHERE slug = 'dogs'), '🐕', 5),
(gen_random_uuid(), 'Dog Grooming', 'dog-grooming', (SELECT id FROM categories WHERE slug = 'dogs'), '✂️', 6),
(gen_random_uuid(), 'Dog Clothing', 'dog-clothing', (SELECT id FROM categories WHERE slug = 'dogs'), '👔', 7),
(gen_random_uuid(), 'Dog Health', 'dog-health', (SELECT id FROM categories WHERE slug = 'dogs'), '💊', 8),
(gen_random_uuid(), 'Dog Training', 'dog-training', (SELECT id FROM categories WHERE slug = 'dogs'), '🎓', 9),
(gen_random_uuid(), 'Dog Bowls & Feeding', 'dog-bowls', (SELECT id FROM categories WHERE slug = 'dogs'), '🥣', 10),
(gen_random_uuid(), 'Dog Crates & Kennels', 'dog-crates', (SELECT id FROM categories WHERE slug = 'dogs'), '🏠', 11),
(gen_random_uuid(), 'Dog Houses', 'dog-houses', (SELECT id FROM categories WHERE slug = 'dogs'), '🏡', 12),
(gen_random_uuid(), 'Dog Carriers', 'dog-carriers', (SELECT id FROM categories WHERE slug = 'dogs'), '👜', 13),
-- Cats L3
(gen_random_uuid(), 'Cat Food', 'cat-food', (SELECT id FROM categories WHERE slug = 'cats'), '🐟', 1),
(gen_random_uuid(), 'Cat Treats', 'cat-treats', (SELECT id FROM categories WHERE slug = 'cats'), '🐟', 2),
(gen_random_uuid(), 'Cat Toys', 'cat-toys', (SELECT id FROM categories WHERE slug = 'cats'), '🎾', 3),
(gen_random_uuid(), 'Cat Furniture', 'cat-furniture', (SELECT id FROM categories WHERE slug = 'cats'), '🐱', 4),
(gen_random_uuid(), 'Cat Litter & Accessories', 'cat-litter', (SELECT id FROM categories WHERE slug = 'cats'), '🚽', 5),
(gen_random_uuid(), 'Cat Grooming', 'cat-grooming', (SELECT id FROM categories WHERE slug = 'cats'), '✂️', 6),
(gen_random_uuid(), 'Cat Health', 'cat-health', (SELECT id FROM categories WHERE slug = 'cats'), '💊', 7),
(gen_random_uuid(), 'Cat Collars', 'cat-collars', (SELECT id FROM categories WHERE slug = 'cats'), '🐱', 8),
(gen_random_uuid(), 'Cat Bowls & Feeding', 'cat-bowls', (SELECT id FROM categories WHERE slug = 'cats'), '🥣', 9),
(gen_random_uuid(), 'Cat Carriers', 'cat-carriers', (SELECT id FROM categories WHERE slug = 'cats'), '👜', 10),
(gen_random_uuid(), 'Cat Beds', 'cat-beds', (SELECT id FROM categories WHERE slug = 'cats'), '🛏️', 11),
-- Birds L3
(gen_random_uuid(), 'Bird Food', 'bird-food', (SELECT id FROM categories WHERE slug = 'birds'), '🌾', 1),
(gen_random_uuid(), 'Bird Cages', 'bird-cages', (SELECT id FROM categories WHERE slug = 'birds'), '🏠', 2),
(gen_random_uuid(), 'Bird Toys', 'bird-toys', (SELECT id FROM categories WHERE slug = 'birds'), '🎾', 3),
(gen_random_uuid(), 'Bird Perches', 'bird-perches', (SELECT id FROM categories WHERE slug = 'birds'), '🪵', 4),
(gen_random_uuid(), 'Bird Health', 'bird-health', (SELECT id FROM categories WHERE slug = 'birds'), '💊', 5),
-- Fish L3
(gen_random_uuid(), 'Fish Food', 'fish-food', (SELECT id FROM categories WHERE slug = 'fish-aquatic'), '🐟', 1),
(gen_random_uuid(), 'Aquariums & Tanks', 'aquariums', (SELECT id FROM categories WHERE slug = 'fish-aquatic'), '🐠', 2),
(gen_random_uuid(), 'Aquarium Filters', 'aquarium-filters', (SELECT id FROM categories WHERE slug = 'fish-aquatic'), '🔧', 3),
(gen_random_uuid(), 'Aquarium Lighting', 'aquarium-lighting', (SELECT id FROM categories WHERE slug = 'fish-aquatic'), '💡', 4),
(gen_random_uuid(), 'Aquarium Heaters', 'aquarium-heaters', (SELECT id FROM categories WHERE slug = 'fish-aquatic'), '🌡️', 5),
(gen_random_uuid(), 'Aquarium Decorations', 'aquarium-decor', (SELECT id FROM categories WHERE slug = 'fish-aquatic'), '🪸', 6),
(gen_random_uuid(), 'Water Care', 'water-care', (SELECT id FROM categories WHERE slug = 'fish-aquatic'), '💧', 7),
-- Small Animals L3
(gen_random_uuid(), 'Small Animal Food', 'small-animal-food', (SELECT id FROM categories WHERE slug = 'small-animals'), '🥕', 1),
(gen_random_uuid(), 'Small Animal Cages', 'small-animal-cages', (SELECT id FROM categories WHERE slug = 'small-animals'), '🏠', 2),
(gen_random_uuid(), 'Small Animal Bedding', 'small-animal-bedding', (SELECT id FROM categories WHERE slug = 'small-animals'), '🛏️', 3),
(gen_random_uuid(), 'Small Animal Toys', 'small-animal-toys', (SELECT id FROM categories WHERE slug = 'small-animals'), '🎾', 4),
(gen_random_uuid(), 'Small Animal Health', 'small-animal-health', (SELECT id FROM categories WHERE slug = 'small-animals'), '💊', 5),
-- Reptiles L3
(gen_random_uuid(), 'Reptile Food', 'reptile-food', (SELECT id FROM categories WHERE slug = 'reptiles'), '🦗', 1),
(gen_random_uuid(), 'Reptile Terrariums', 'reptile-terrariums', (SELECT id FROM categories WHERE slug = 'reptiles'), '🦎', 2),
(gen_random_uuid(), 'Reptile Lighting', 'reptile-lighting', (SELECT id FROM categories WHERE slug = 'reptiles'), '💡', 3),
(gen_random_uuid(), 'Reptile Heating', 'reptile-heating', (SELECT id FROM categories WHERE slug = 'reptiles'), '🌡️', 4),
(gen_random_uuid(), 'Reptile Substrate', 'reptile-substrate', (SELECT id FROM categories WHERE slug = 'reptiles'), '🪨', 5),
-- Kids - Toys & Games L3
(gen_random_uuid(), 'Action Figures', 'toys-action', (SELECT id FROM categories WHERE slug = 'toys-games'), '🦸', 1),
(gen_random_uuid(), 'Building Toys', 'toys-building', (SELECT id FROM categories WHERE slug = 'toys-games'), '🧱', 2),
(gen_random_uuid(), 'Dolls & Accessories', 'toys-dolls', (SELECT id FROM categories WHERE slug = 'toys-games'), '🧸', 3),
(gen_random_uuid(), 'Educational Toys', 'toys-educational', (SELECT id FROM categories WHERE slug = 'toys-games'), '🎓', 4),
(gen_random_uuid(), 'Games & Puzzles', 'toys-games-puzzles', (SELECT id FROM categories WHERE slug = 'toys-games'), '🧩', 5),
(gen_random_uuid(), 'Outdoor Play', 'toys-outdoor', (SELECT id FROM categories WHERE slug = 'toys-games'), '🌳', 6),
(gen_random_uuid(), 'Ride-On Toys', 'toys-rideon', (SELECT id FROM categories WHERE slug = 'toys-games'), '🚗', 7),
(gen_random_uuid(), 'Plush & Stuffed Animals', 'toys-plush', (SELECT id FROM categories WHERE slug = 'toys-games'), '🧸', 8),
(gen_random_uuid(), 'Arts & Crafts', 'toys-arts', (SELECT id FROM categories WHERE slug = 'toys-games'), '🎨', 9),
(gen_random_uuid(), 'Pretend Play', 'toys-pretend', (SELECT id FROM categories WHERE slug = 'toys-games'), '🎭', 10),
(gen_random_uuid(), 'Baby & Toddler Toys', 'toys-baby', (SELECT id FROM categories WHERE slug = 'toys-games'), '👶', 11),
-- Kids - Baby Gear L3
(gen_random_uuid(), 'Strollers', 'babygear-strollers', (SELECT id FROM categories WHERE slug = 'baby-gear'), '🚼', 1),
(gen_random_uuid(), 'Car Seats', 'babygear-carseats', (SELECT id FROM categories WHERE slug = 'baby-gear'), '🚗', 2),
(gen_random_uuid(), 'Baby Carriers', 'babygear-carriers', (SELECT id FROM categories WHERE slug = 'baby-gear'), '👶', 3),
(gen_random_uuid(), 'Swings & Bouncers', 'babygear-swings', (SELECT id FROM categories WHERE slug = 'baby-gear'), '🪑', 4),
(gen_random_uuid(), 'High Chairs', 'babygear-highchairs', (SELECT id FROM categories WHERE slug = 'baby-gear'), '🪑', 5),
(gen_random_uuid(), 'Baby Monitors', 'babygear-monitors', (SELECT id FROM categories WHERE slug = 'baby-gear'), '📹', 6),
-- Kids - Nursery L3
(gen_random_uuid(), 'Cribs & Bassinets', 'nursery-cribs', (SELECT id FROM categories WHERE slug = 'nursery'), '🛏️', 1),
(gen_random_uuid(), 'Changing Tables', 'nursery-changing', (SELECT id FROM categories WHERE slug = 'nursery'), '👶', 2),
(gen_random_uuid(), 'Nursery Furniture', 'nursery-furniture', (SELECT id FROM categories WHERE slug = 'nursery'), '🏠', 3),
(gen_random_uuid(), 'Nursery Bedding', 'nursery-bedding', (SELECT id FROM categories WHERE slug = 'nursery'), '🛏️', 4),
(gen_random_uuid(), 'Nursery Décor', 'nursery-decor', (SELECT id FROM categories WHERE slug = 'nursery'), '🖼️', 5),
-- Diapering L3
(gen_random_uuid(), 'Disposable Diapers', 'diaper-disposable', (SELECT id FROM categories WHERE slug = 'diapering'), '👶', 1),
(gen_random_uuid(), 'Cloth Diapers', 'diaper-cloth', (SELECT id FROM categories WHERE slug = 'diapering'), '👶', 2),
(gen_random_uuid(), 'Wipes & Warmers', 'diaper-wipes', (SELECT id FROM categories WHERE slug = 'diapering'), '🧻', 3),
(gen_random_uuid(), 'Diaper Rash Care', 'diaper-rash', (SELECT id FROM categories WHERE slug = 'diapering'), '💊', 4),
(gen_random_uuid(), 'Potty Training', 'diaper-potty', (SELECT id FROM categories WHERE slug = 'diapering'), '🚽', 5),
-- Automotive - Vehicles L3
(gen_random_uuid(), 'Cars', 'cars', (SELECT id FROM categories WHERE slug = 'vehicles'), '🚗', 1),
(gen_random_uuid(), 'SUVs & Crossovers', 'suvs', (SELECT id FROM categories WHERE slug = 'vehicles'), '🚙', 2),
(gen_random_uuid(), 'Motorcycles', 'motorcycles', (SELECT id FROM categories WHERE slug = 'vehicles'), '🏍️', 3),
(gen_random_uuid(), 'Trucks', 'trucks', (SELECT id FROM categories WHERE slug = 'vehicles'), '🛻', 4),
(gen_random_uuid(), 'Vans & Buses', 'vans-buses', (SELECT id FROM categories WHERE slug = 'vehicles'), '🚐', 5),
(gen_random_uuid(), 'Campers', 'campers', (SELECT id FROM categories WHERE slug = 'vehicles'), '🚐', 6),
(gen_random_uuid(), 'Boats', 'boats', (SELECT id FROM categories WHERE slug = 'vehicles'), '⛵', 7),
(gen_random_uuid(), 'ATVs', 'atvs', (SELECT id FROM categories WHERE slug = 'vehicles'), '🏎️', 8),
-- Auto Parts L3
(gen_random_uuid(), 'Engine Parts', 'engine-parts', (SELECT id FROM categories WHERE slug = 'auto-parts'), '🔧', 1),
(gen_random_uuid(), 'Brakes & Suspension', 'brakes-suspension', (SELECT id FROM categories WHERE slug = 'auto-parts'), '🔧', 2),
(gen_random_uuid(), 'Body Parts', 'body-parts', (SELECT id FROM categories WHERE slug = 'auto-parts'), '🚗', 3),
(gen_random_uuid(), 'Interior Parts', 'interior-parts', (SELECT id FROM categories WHERE slug = 'auto-parts'), '🚗', 4),
(gen_random_uuid(), 'Electrical Parts', 'electrical-parts', (SELECT id FROM categories WHERE slug = 'auto-parts'), '⚡', 5),
(gen_random_uuid(), 'Wheels & Tires', 'wheels-tires', (SELECT id FROM categories WHERE slug = 'auto-parts'), '🛞', 6),
(gen_random_uuid(), 'Exhaust', 'exhaust', (SELECT id FROM categories WHERE slug = 'auto-parts'), '💨', 7),
(gen_random_uuid(), 'Transmission', 'transmission', (SELECT id FROM categories WHERE slug = 'auto-parts'), '🔧', 8),
-- Auto Accessories L3
(gen_random_uuid(), 'Car Audio', 'car-audio', (SELECT id FROM categories WHERE slug = 'auto-accessories'), '🔊', 1),
(gen_random_uuid(), 'Car Electronics', 'car-electronics', (SELECT id FROM categories WHERE slug = 'auto-accessories'), '📱', 2),
(gen_random_uuid(), 'Interior Accessories', 'auto-interior-accessories', (SELECT id FROM categories WHERE slug = 'auto-accessories'), '🚗', 3),
(gen_random_uuid(), 'Exterior Accessories', 'auto-exterior-accessories', (SELECT id FROM categories WHERE slug = 'auto-accessories'), '🚗', 4),
(gen_random_uuid(), 'Car Care', 'car-care', (SELECT id FROM categories WHERE slug = 'auto-accessories'), '🧼', 5)
ON CONFLICT (slug) DO NOTHING;
;
