
-- MASSIVE L3 RESTORATION - SPORTS, COLLECTIBLES, REAL ESTATE, HEALTH, HOBBIES
-- Team Sports L3
INSERT INTO categories (id, name, slug, parent_id, icon, display_order) VALUES
(gen_random_uuid(), 'Football/Soccer', 'football-soccer', (SELECT id FROM categories WHERE slug = 'team-sports'), '⚽', 1),
(gen_random_uuid(), 'Basketball', 'basketball', (SELECT id FROM categories WHERE slug = 'team-sports'), '🏀', 2),
(gen_random_uuid(), 'Baseball', 'baseball', (SELECT id FROM categories WHERE slug = 'team-sports'), '⚾', 3),
(gen_random_uuid(), 'American Football', 'american-football', (SELECT id FROM categories WHERE slug = 'team-sports'), '🏈', 4),
(gen_random_uuid(), 'Hockey', 'hockey', (SELECT id FROM categories WHERE slug = 'team-sports'), '🏒', 5),
(gen_random_uuid(), 'Volleyball', 'volleyball', (SELECT id FROM categories WHERE slug = 'team-sports'), '🏐', 6),
(gen_random_uuid(), 'Rugby', 'rugby', (SELECT id FROM categories WHERE slug = 'team-sports'), '🏉', 7),
-- Fitness L3
(gen_random_uuid(), 'Cardio Equipment', 'cardio-equipment', (SELECT id FROM categories WHERE slug = 'fitness'), '🏃', 1),
(gen_random_uuid(), 'Strength Equipment', 'strength-equipment', (SELECT id FROM categories WHERE slug = 'fitness'), '🏋️', 2),
(gen_random_uuid(), 'Yoga & Pilates', 'yoga-pilates', (SELECT id FROM categories WHERE slug = 'fitness'), '🧘', 3),
(gen_random_uuid(), 'Fitness Accessories', 'fitness-accessories', (SELECT id FROM categories WHERE slug = 'fitness'), '🎽', 4),
(gen_random_uuid(), 'Home Gym', 'home-gym', (SELECT id FROM categories WHERE slug = 'fitness'), '🏠', 5),
-- Outdoor Recreation L3
(gen_random_uuid(), 'Camping & Hiking', 'camping-hiking', (SELECT id FROM categories WHERE slug = 'outdoor-recreation'), '🏕️', 1),
(gen_random_uuid(), 'Cycling', 'cycling', (SELECT id FROM categories WHERE slug = 'outdoor-recreation'), '🚴', 2),
(gen_random_uuid(), 'Fishing', 'fishing', (SELECT id FROM categories WHERE slug = 'outdoor-recreation'), '🎣', 3),
(gen_random_uuid(), 'Hunting', 'hunting', (SELECT id FROM categories WHERE slug = 'outdoor-recreation'), '🏹', 4),
(gen_random_uuid(), 'Winter Sports', 'winter-sports', (SELECT id FROM categories WHERE slug = 'outdoor-recreation'), '⛷️', 5),
-- Water Sports L3
(gen_random_uuid(), 'Swimming', 'swimming', (SELECT id FROM categories WHERE slug = 'water-sports'), '🏊', 1),
(gen_random_uuid(), 'Surfing', 'surfing', (SELECT id FROM categories WHERE slug = 'water-sports'), '🏄', 2),
(gen_random_uuid(), 'Kayaking & Canoeing', 'kayaking', (SELECT id FROM categories WHERE slug = 'water-sports'), '🛶', 3),
(gen_random_uuid(), 'Diving & Snorkeling', 'diving', (SELECT id FROM categories WHERE slug = 'water-sports'), '🤿', 4),
-- Trading Cards L3
(gen_random_uuid(), 'Pokémon Cards', 'coll-pokemon', (SELECT id FROM categories WHERE slug = 'coll-trading-cards'), '🃏', 1),
(gen_random_uuid(), 'Magic: The Gathering', 'coll-mtg', (SELECT id FROM categories WHERE slug = 'coll-trading-cards'), '🃏', 2),
(gen_random_uuid(), 'Yu-Gi-Oh!', 'coll-yugioh', (SELECT id FROM categories WHERE slug = 'coll-trading-cards'), '🃏', 3),
(gen_random_uuid(), 'Sports Trading Cards', 'coll-sports-cards', (SELECT id FROM categories WHERE slug = 'coll-trading-cards'), '🃏', 4),
(gen_random_uuid(), 'One Piece TCG', 'coll-onepiece', (SELECT id FROM categories WHERE slug = 'coll-trading-cards'), '🃏', 5),
(gen_random_uuid(), 'Dragon Ball Cards', 'coll-dragonball', (SELECT id FROM categories WHERE slug = 'coll-trading-cards'), '🃏', 6),
(gen_random_uuid(), 'Graded Cards', 'coll-graded-cards', (SELECT id FROM categories WHERE slug = 'coll-trading-cards'), '🃏', 7),
-- Coins & Currency L3
(gen_random_uuid(), 'Gold Coins', 'coins-gold', (SELECT id FROM categories WHERE slug = 'coins-currency'), '🪙', 1),
(gen_random_uuid(), 'Silver Coins', 'coins-silver', (SELECT id FROM categories WHERE slug = 'coins-currency'), '🪙', 2),
(gen_random_uuid(), 'Ancient Coins', 'coins-ancient', (SELECT id FROM categories WHERE slug = 'coins-currency'), '🪙', 3),
(gen_random_uuid(), 'World Coins', 'coins-world', (SELECT id FROM categories WHERE slug = 'coins-currency'), '🪙', 4),
(gen_random_uuid(), 'Bulgarian Coins', 'coins-bulgarian', (SELECT id FROM categories WHERE slug = 'coins-currency'), '🪙', 5),
(gen_random_uuid(), 'Paper Money', 'coins-paper-money', (SELECT id FROM categories WHERE slug = 'coins-currency'), '💵', 6),
(gen_random_uuid(), 'Bullion', 'coins-bullion', (SELECT id FROM categories WHERE slug = 'coins-currency'), '🪙', 7),
-- Antiques L3
(gen_random_uuid(), 'Antique Furniture', 'antiques-furniture', (SELECT id FROM categories WHERE slug = 'antiques'), '🪑', 1),
(gen_random_uuid(), 'Antique Art', 'antiques-art', (SELECT id FROM categories WHERE slug = 'antiques'), '🖼️', 2),
(gen_random_uuid(), 'Antique Clocks', 'antiques-clocks', (SELECT id FROM categories WHERE slug = 'antiques'), '🕰️', 3),
(gen_random_uuid(), 'Vintage Porcelain', 'antiques-porcelain', (SELECT id FROM categories WHERE slug = 'antiques'), '🏺', 4),
(gen_random_uuid(), 'Antique Jewelry', 'antiques-jewelry', (SELECT id FROM categories WHERE slug = 'antiques'), '💎', 5),
(gen_random_uuid(), 'Antique Silverware', 'antiques-silverware', (SELECT id FROM categories WHERE slug = 'antiques'), '🥄', 6),
(gen_random_uuid(), 'Antique Books & Maps', 'antiques-books', (SELECT id FROM categories WHERE slug = 'antiques'), '📚', 7),
-- Real Estate - Residential Sales L3
(gen_random_uuid(), 'Studios for Sale', 'studios-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏠', 1),
(gen_random_uuid(), '1-Bedroom Apartments', 'apartments-1room-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏠', 2),
(gen_random_uuid(), '2-Room Apartments', 'apartments-2room-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏠', 3),
(gen_random_uuid(), '3-Room Apartments', 'apartments-3room-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏠', 4),
(gen_random_uuid(), 'Maisonettes', 'maisonettes-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏠', 5),
(gen_random_uuid(), 'Penthouses', 'penthouses-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏢', 6),
(gen_random_uuid(), 'Detached Houses', 'detached-houses-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏡', 7),
(gen_random_uuid(), 'Villas', 'villas-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏰', 8),
(gen_random_uuid(), 'Country Houses', 'country-houses-sale', (SELECT id FROM categories WHERE slug = 'residential-sales'), '🏡', 9),
-- Real Estate - Rentals L3
(gen_random_uuid(), 'Studios for Rent', 'studios-rent', (SELECT id FROM categories WHERE slug = 'residential-rentals'), '🔑', 1),
(gen_random_uuid(), '1-Bedroom Rent', 'apartments-1room-rent', (SELECT id FROM categories WHERE slug = 'residential-rentals'), '🔑', 2),
(gen_random_uuid(), '2-Room Rent', 'apartments-2room-rent', (SELECT id FROM categories WHERE slug = 'residential-rentals'), '🔑', 3),
(gen_random_uuid(), '3-Room Rent', 'apartments-3room-rent', (SELECT id FROM categories WHERE slug = 'residential-rentals'), '🔑', 4),
(gen_random_uuid(), 'Houses for Rent', 'houses-rent', (SELECT id FROM categories WHERE slug = 'residential-rentals'), '🔑', 5),
(gen_random_uuid(), 'Furnished Rentals', 'furnished-rentals', (SELECT id FROM categories WHERE slug = 'residential-rentals'), '🛋️', 6),
(gen_random_uuid(), 'Short-Term Rentals', 'short-term-rentals', (SELECT id FROM categories WHERE slug = 'residential-rentals'), '📅', 7),
(gen_random_uuid(), 'Student Housing', 'student-housing', (SELECT id FROM categories WHERE slug = 'residential-rentals'), '🎓', 8),
-- Real Estate - Commercial L3
(gen_random_uuid(), 'Offices for Sale', 'offices-commercial-sale', (SELECT id FROM categories WHERE slug = 'commercial'), '🏢', 1),
(gen_random_uuid(), 'Retail Shops', 'retail-shops-sale', (SELECT id FROM categories WHERE slug = 'commercial'), '🏪', 2),
(gen_random_uuid(), 'Warehouses', 'warehouses-sale', (SELECT id FROM categories WHERE slug = 'commercial'), '🏭', 3),
(gen_random_uuid(), 'Industrial Buildings', 'industrial-buildings-sale', (SELECT id FROM categories WHERE slug = 'commercial'), '🏭', 4),
(gen_random_uuid(), 'Restaurants & Cafes', 'restaurants-sale', (SELECT id FROM categories WHERE slug = 'commercial'), '🍽️', 5),
(gen_random_uuid(), 'Hotels', 'hotels-sale', (SELECT id FROM categories WHERE slug = 'commercial'), '🏨', 6),
-- Real Estate - Land L3
(gen_random_uuid(), 'Building Plots', 'building-plots', (SELECT id FROM categories WHERE slug = 'land'), '🏗️', 1),
(gen_random_uuid(), 'Agricultural Land', 'agricultural-land', (SELECT id FROM categories WHERE slug = 'land'), '🌾', 2),
(gen_random_uuid(), 'Arable Land', 'arable-land', (SELECT id FROM categories WHERE slug = 'land'), '🌱', 3),
(gen_random_uuid(), 'Orchards', 'orchards', (SELECT id FROM categories WHERE slug = 'land'), '🍎', 4),
(gen_random_uuid(), 'Vineyards', 'vineyards', (SELECT id FROM categories WHERE slug = 'land'), '🍇', 5),
(gen_random_uuid(), 'Forest Land', 'forest-land', (SELECT id FROM categories WHERE slug = 'land'), '🌲', 6),
-- Health - Supplements L3
(gen_random_uuid(), 'Vitamins', 'vitamins-supplements', (SELECT id FROM categories WHERE slug = 'supplements-vitamins'), '💊', 1),
(gen_random_uuid(), 'Omega & Fish Oils', 'omega-fish-oils', (SELECT id FROM categories WHERE slug = 'supplements-vitamins'), '🐟', 2),
(gen_random_uuid(), 'Probiotics', 'probiotics-gut-health', (SELECT id FROM categories WHERE slug = 'supplements-vitamins'), '🦠', 3),
(gen_random_uuid(), 'Collagen & Beauty', 'collagen-beauty', (SELECT id FROM categories WHERE slug = 'supplements-vitamins'), '✨', 4),
(gen_random_uuid(), 'Joint & Mobility', 'joint-mobility', (SELECT id FROM categories WHERE slug = 'supplements-vitamins'), '🦴', 5),
(gen_random_uuid(), 'Immune Support', 'immune-support', (SELECT id FROM categories WHERE slug = 'supplements-vitamins'), '🛡️', 6),
(gen_random_uuid(), 'Sleep & Relaxation', 'sleep-relaxation', (SELECT id FROM categories WHERE slug = 'supplements-vitamins'), '😴', 7),
-- Health - Sports Nutrition L3
(gen_random_uuid(), 'Protein Powders', 'protein-powders', (SELECT id FROM categories WHERE slug = 'sports-fitness-nutrition'), '💪', 1),
(gen_random_uuid(), 'Pre-Workout', 'pre-workout', (SELECT id FROM categories WHERE slug = 'sports-fitness-nutrition'), '⚡', 2),
(gen_random_uuid(), 'BCAAs', 'bcaas', (SELECT id FROM categories WHERE slug = 'sports-fitness-nutrition'), '💪', 3),
(gen_random_uuid(), 'Creatine', 'creatine', (SELECT id FROM categories WHERE slug = 'sports-fitness-nutrition'), '💪', 4),
(gen_random_uuid(), 'Weight Management', 'weight-management', (SELECT id FROM categories WHERE slug = 'sports-fitness-nutrition'), '⚖️', 5),
(gen_random_uuid(), 'Mass Gainers', 'mass-gainers', (SELECT id FROM categories WHERE slug = 'sports-fitness-nutrition'), '💪', 6),
-- Hobbies - Handmade L3
(gen_random_uuid(), 'Handmade Jewelry', 'handmade-jewelry', (SELECT id FROM categories WHERE slug = 'handmade'), '💎', 1),
(gen_random_uuid(), 'Handmade Clothing', 'handmade-clothing', (SELECT id FROM categories WHERE slug = 'handmade'), '👕', 2),
(gen_random_uuid(), 'Home Décor Crafts', 'home-decor-crafts', (SELECT id FROM categories WHERE slug = 'handmade'), '🏠', 3),
(gen_random_uuid(), 'Craft Supplies', 'craft-supplies', (SELECT id FROM categories WHERE slug = 'handmade'), '✂️', 4),
(gen_random_uuid(), 'Bulgarian Crafts', 'handmade-bulgarian', (SELECT id FROM categories WHERE slug = 'handmade'), '🇧🇬', 5),
-- Hobbies - Musical Instruments L3
(gen_random_uuid(), 'Guitars & Basses', 'guitars-basses', (SELECT id FROM categories WHERE slug = 'musical-instruments'), '🎸', 1),
(gen_random_uuid(), 'Keyboards & Pianos', 'keyboards-pianos', (SELECT id FROM categories WHERE slug = 'musical-instruments'), '🎹', 2),
(gen_random_uuid(), 'Drums & Percussion', 'drums-percussion', (SELECT id FROM categories WHERE slug = 'musical-instruments'), '🥁', 3),
(gen_random_uuid(), 'Wind Instruments', 'wind-instruments', (SELECT id FROM categories WHERE slug = 'musical-instruments'), '🎺', 4),
(gen_random_uuid(), 'String Instruments', 'string-instruments', (SELECT id FROM categories WHERE slug = 'musical-instruments'), '🎻', 5),
(gen_random_uuid(), 'DJ Equipment', 'dj-equipment', (SELECT id FROM categories WHERE slug = 'musical-instruments'), '🎧', 6),
(gen_random_uuid(), 'Recording Equipment', 'recording-equipment', (SELECT id FROM categories WHERE slug = 'musical-instruments'), '🎤', 7)
ON CONFLICT (slug) DO NOTHING;
;
